/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.groupChat;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import model.Room;
import model.User;
import model.UserInARoom;
import service.ClientProcess;
import views.SingleChatFrm;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import views.ChatHomeFrm;
import views.SearchUserForSingleChatFrm;

/**
 *
 * @author LENOVO
 */
public class GroupChatRoomsFrm extends javax.swing.JFrame {

    /**
     * Creates new form GroupChatRoomsFrm
     */
    private JFrame mainFrame = this;
    private ArrayList<Room> listGroupChatRooms = new ArrayList<>();
    private ClientProcess clientProcess = null;
    
    public GroupChatRoomsFrm(ClientProcess clientProcess) {
        initComponents();
     this.clientProcess = clientProcess;
      this.clientProcess.setCurrentFrame(this);
      
      //UI
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.getContentPane().setBackground(Color.getHSBColor(106, 52, 50));
        setTitle("Danh sách phòng chat nhóm của "+clientProcess.getUser().getUserName());
        groupChatImage.setIcon(new ImageIcon("groupChat.png"));
      
        int userId = clientProcess.getUser().getId();
        clientProcess.getGroupChatRooms(userId);
        
        String[][] data = new String[listGroupChatRooms.size()][2];
        String[] columnNames = {"RoomId","RoomName"};
        for(int i=0;i<listGroupChatRooms.size();i++){
            Room room = listGroupChatRooms.get(i);
            data[i][0] = room.getId()+"";
            
//            // lay ra ten cua user con lai trong phong
//            User currenUser = clientProcess.getUser();
//            User theRestUserInTheRoom = new User();
//            ArrayList<UserInARoom> listUsersInSingleChatRoom = room.getListUserInARoom();
//            for(UserInARoom u : listUsersInSingleChatRoom){
//                if(u.getUser().getId() != currenUser.getId()) theRestUserInTheRoom = u.getUser();
//            }
            data[i][1] = listGroupChatRooms.get(i).getName();
//            data[i][2] = theRestUserInTheRoom.getFullName();
//            data[i][3] = theRestUserInTheRoom.getOnlineStatus()+"";
        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblGroupChat.setModel(dtm);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTheRestUserName = new javax.swing.JLabel();
        btnTaoPhongMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGroupChat = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        groupChatImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTheRestUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTheRestUserName.setText("Group chat gan day:");

        btnTaoPhongMoi.setText("Tao phong moi");
        btnTaoPhongMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhongMoiActionPerformed(evt);
            }
        });

        tblGroupChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Lap Trinh Mang nhom 11"},
                {"2", "Lap Trinh Web"},
                {"3", "Phan tich thiet ke"}
            },
            new String [] {
                "id", "name"
            }
        ));
        tblGroupChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupChatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGroupChat);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(labelTheRestUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnTaoPhongMoi)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(groupChatImage, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaoPhongMoi)
                    .addComponent(labelTheRestUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(groupChatImage, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void receiveRoomsAndDisplayData(ArrayList<Room> listRoom){
        listGroupChatRooms = listRoom;
        // hien thi
       String[][] data = new String[listGroupChatRooms.size()][2];
        String[] columnNames = {"RoomId","RoomName"};
        for(int i=0;i<listGroupChatRooms.size();i++){
            Room room = listGroupChatRooms.get(i);
            data[i][0] = room.getId()+"";
            
//            // lay ra ten cua user con lai trong phong
//            User currenUser = clientProcess.getUser();
//            User theRestUserInTheRoom = new User();
//            ArrayList<UserInARoom> listUsersInSingleChatRoom = room.getListUserInARoom();
//            for(UserInARoom u : listUsersInSingleChatRoom){
//                if(u.getUser().getId() != currenUser.getId()) theRestUserInTheRoom = u.getUser();
//            }
            data[i][1] = listGroupChatRooms.get(i).getName();
//            data[i][2] = theRestUserInTheRoom.getFullName();
//            data[i][3] = theRestUserInTheRoom.getOnlineStatus()+"";
        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblGroupChat.setModel(dtm);
        
        
    }
    private void tblGroupChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupChatMouseClicked
        // TODO add your handling code here:
         int column = tblGroupChat.getColumnModel().
                        getColumnIndexAtX(evt.getX()); // 
                int row = evt.getY()/tblGroupChat.getRowHeight(); 
 
                if (row < tblGroupChat.getRowCount() && row >= 0 && 
                            column < tblGroupChat.getColumnCount() && column >= 0) {
                   Room room = listGroupChatRooms.get(row);
                   System.out.println("room" + room.getListUserInARoom().get(0).getUser().getFullName());
                   clientProcess.setRoom(room);
                   new GroupChatFrm(clientProcess).setVisible(true);
                   mainFrame.dispose();
                }
    }//GEN-LAST:event_tblGroupChatMouseClicked

    private void btnTaoPhongMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhongMoiActionPerformed
        // TODO add your handling code here:
        new CreateNewGroupFrm(clientProcess).setVisible(true);
        mainFrame.dispose();
    }//GEN-LAST:event_btnTaoPhongMoiActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new ChatHomeFrm(clientProcess).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTaoPhongMoi;
    private javax.swing.JLabel groupChatImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTheRestUserName;
    private javax.swing.JTable tblGroupChat;
    // End of variables declaration//GEN-END:variables
}
