/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import service.ClientProcess;
import views.groupChat.GroupChatFrm;
import views.groupChat.GroupChatRoomsFrm;
import javax.swing.JFrame;
import views.friend.FriendFrm;

/**
 *
 * @author LENOVO
 */
public class ChatHomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form ChatFrm
     */
    private ClientProcess clientProcess;
    public ChatHomeFrm(ClientProcess clientProcess) {
        initComponents();
        this.clientProcess = clientProcess;
        
        //gui broadcast trang thai dang nhap
        clientProcess.sendOnlineStatus();
        
        //UI
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.getContentPane().setBackground(Color.getHSBColor(106, 52, 50));
        setTitle("Trang chủ");
        homeImage.setIcon(new ImageIcon("home.png"));
        
        txtUserFullName.setText("Xin chào, "+clientProcess.getUser().getFullName()+"!");
        
        btnSingleChat.addActionListener((e) -> {
           new SingleChatRoomsFrm(clientProcess).setVisible(true);
           this.dispose();
        });
        btnFriend.addActionListener((e) -> {
           new FriendFrm(clientProcess).setVisible(true);
           this.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSingleChat = new javax.swing.JButton();
        btnGroupChat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUserFullName = new javax.swing.JLabel();
        btnFriend = new javax.swing.JButton();
        homeImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSingleChat.setText("Single Chat");

        btnGroupChat.setText("Group Chat");
        btnGroupChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupChatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Trang chủ");

        txtUserFullName.setText("Xin chào, @userFullName");

        btnFriend.setText("Friend");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFriend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGroupChat, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(btnSingleChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtUserFullName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(homeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtUserFullName)
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnSingleChat)
                .addGap(18, 18, 18)
                .addComponent(btnGroupChat)
                .addGap(18, 18, 18)
                .addComponent(btnFriend)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGroupChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupChatActionPerformed
        // TODO add your handling code here:
       new GroupChatRoomsFrm(clientProcess).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnGroupChatActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFriend;
    private javax.swing.JButton btnGroupChat;
    private javax.swing.JButton btnSingleChat;
    private javax.swing.JLabel homeImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtUserFullName;
    // End of variables declaration//GEN-END:variables
}
