/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import model.Room;
import model.User;
import model.UserInARoom;
import service.ClientProcess;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class SingleChatRoomsFrm extends javax.swing.JFrame {

    /**
     * Creates new form SingleChatRoomsFrm
     */
    private JFrame mainFrame = this;
    private ArrayList<Room> listSingleChatRooms;
    private ClientProcess clientProcess;
    public SingleChatRoomsFrm(ClientProcess clientProcess) {
        initComponents();
        this.clientProcess = clientProcess;
        
        //UI
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.getContentPane().setBackground(Color.getHSBColor(106, 52, 50));
        setTitle("Danh sách phòng chat đơn của "+clientProcess.getUser().getUserName());
        singleChatImage.setIcon(new ImageIcon("singleChat.png"));
        
        clientProcess.setCurrentFrame(this);
        // lay cac single chat rooms ung voi nguoi dung tren server ve
        int userId = clientProcess.getUser().getId();
        // gui request lên server để lấy các room 
        clientProcess.getSingleChatRooms(userId);
        
        
    }
    
    public void receiveRoomsAndDisplayData(ArrayList<Room> listRoom){
        listSingleChatRooms = listRoom;
        // hien thi
        String[][] data = new String[listSingleChatRooms.size()][4];
        String[] columnNames = {"id room","user name","họ tên","online status"};
        for(int i=0;i<listSingleChatRooms.size();i++){
            Room room = listSingleChatRooms.get(i);
            data[i][0] = room.getId()+"";
            
            // lay ra ten cua user con lai trong phong
            User currenUser = clientProcess.getUser();
            User theRestUserInTheRoom = new User();
            ArrayList<UserInARoom> listUsersInSingleChatRoom = room.getListUserInARoom();
            for(UserInARoom u : listUsersInSingleChatRoom){
                if(u.getUser().getId() != currenUser.getId()) theRestUserInTheRoom = u.getUser();
            }
            data[i][1] = theRestUserInTheRoom.getUserName();
            data[i][2] = theRestUserInTheRoom.getFullName();
            data[i][3] = theRestUserInTheRoom.getOnlineStatus()+"";
        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblRooms.setModel(dtm);
        
        btnSearchForUser.addActionListener((e) -> {
            new SearchUserForSingleChatFrm(clientProcess).setVisible(true);
            this.dispose();
        });
        
        tblRooms.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = tblRooms.getColumnModel().
                        getColumnIndexAtX(e.getX()); // 
                int row = e.getY()/tblRooms.getRowHeight(); 
 
                if (row < tblRooms.getRowCount() && row >= 0 && 
                            column < tblRooms.getColumnCount() && column >= 0) {
                   Room room = listSingleChatRooms.get(row);
                   // set room cho tien trinh clientHandler
                   clientProcess.setRoom(room);
                   new SingleChatFrm(clientProcess).setVisible(true);
                   mainFrame.dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnSearchForUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        singleChatImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Chat đơn gần đây");

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id room", "user name", "full name", "online status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRooms);

        jScrollPane2.setViewportView(jScrollPane1);

        btnSearchForUser.setText("Tìm người chat");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92)
                        .addComponent(btnSearchForUser))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(singleChatImage, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnSearchForUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(singleChatImage, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRoomsMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new ChatHomeFrm(clientProcess).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchForUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel singleChatImage;
    private javax.swing.JTable tblRooms;
    // End of variables declaration//GEN-END:variables
}
