/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.friend;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import model.User;
import service.ClientProcess;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Friend;
import model.Room;
import model.UserInARoom;
import views.ChatHomeFrm;
import views.SingleChatFrm;


/**
 *
 * @author QUANG
 */

public class FriendFrm extends javax.swing.JFrame {

    /**
     * Creates new form FriendFrm
     */
    String listFriendToScreen = "";
    private ClientProcess clientProcess;
    private User user;
    private ArrayList<Friend> listFriend;
    private ArrayList<User> listUser;
    private User otherUser;
    public FriendFrm(ClientProcess clientProcess) {
        initComponents();
        this.clientProcess = clientProcess;
        
        //UI
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.getContentPane().setBackground(Color.getHSBColor(106, 52, 50));
        setTitle("Bạn bè");
        friendsImage.setIcon(new ImageIcon("friends.png"));
        
        this.user = clientProcess.getUser();
        clientProcess.setCurrentFrame(this);
        
//      Nút back
        btnBack.addActionListener((e) -> {
            new ChatHomeFrm(clientProcess).setVisible(true);
            this.dispose();
        });
        clientProcess.getListFriend(user);
        
//       Nút friend request
        btnFriendRequest.addActionListener((e) -> {
           FriendRequestDialog fr = new FriendRequestDialog(this, true, clientProcess,this.listFriend,this.user);
           fr.setVisible(true);
        });
//       Nút Add friend
         btnAddFriend.addActionListener((e) -> {
           AddNewFriendDialog fr = new AddNewFriendDialog(this, true, clientProcess,this.listFriend,this.user);
           fr.setVisible(true);
        });
//       Lấy thông tin bạn bè từ bảng sang form
        tblFriend.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int r = tblFriend.getSelectedRow();
                jtfName.setText( listUser.get(r).getFullName() );
                jtfEmail.setText(listUser.get(r).getEmail());
                jtfPhone.setText(listUser.get(r).getPhoneNo());
                otherUser = listUser.get(r);
            }
        });
        btnRemove.addActionListener((x) -> {
            int r = tblFriend.getSelectedRow();
            clientProcess.deleteFriend(this.listFriend.get(r));
            this.listFriend.remove(r);
            loadTableFriend(this.listFriend);
        });

    }
    
    public void receiveListFriend(ArrayList<Friend> list ){
        this.listFriend = list;
        loadTableFriend(this.listFriend);
    }
    
    public void loadTableFriend(ArrayList<Friend> list ){
        ArrayList<User> listUserDisplay = new ArrayList<>();
        for(Friend i : list){
            if(i.getFriendStatus() == 1){
                if(i.getUser1().getId() != user.getId()) listUserDisplay.add(i.getUser1());
                else listUserDisplay.add(i.getUser2());
//                System.out.println(i.getId() + " " + i.getUser1().getFullName()+ " " + i.getUser2().getFullName() + "\n");
            }
        }
        String[][] data = new String[listUserDisplay.size()][4];
        String[] columnNames = {"Full name","Email","Phone","Online status"};
        for(int i=0;i<listUserDisplay.size();i++){
            User userA = listUserDisplay.get(i);
            data[i][0] = userA.getFullName()+"";
            data[i][1] = userA.getEmail() + "";
            data[i][2] = userA.getPhoneNo() +"" ;
            if(userA.getOnlineStatus() == 1){
                data[i][3] = "Online";
            }
            else data[i][3] = "Offline";
        }
        this.listUser = listUserDisplay;
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblFriend.setModel(dtm);
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    
    public ArrayList<Friend> getListFriend() {
        return listFriend;
    }

    public void setListFriend(ArrayList<Friend> listFriend) {
        this.listFriend = listFriend;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFriend = new javax.swing.JTable();
        btnFriendRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jtfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPhone = new javax.swing.JTextField();
        btnChat = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnAddFriend = new javax.swing.JButton();
        friendsImage = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("List Friend");

        tblFriend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full name", "Email", "Phone"
            }
        ));
        jScrollPane2.setViewportView(tblFriend);

        btnFriendRequest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFriendRequest.setText("Friend request");
        btnFriendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriendRequestActionPerformed(evt);
            }
        });

        btnBack.setText("Back");

        jtfName.setEditable(false);
        jtfName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Email");

        jtfEmail.setEditable(false);
        jtfEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Phone");

        jtfPhone.setEditable(false);
        jtfPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnChat.setText("Chat");
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAddFriend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddFriend.setText("Add new friend");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(friendsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnFriendRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(btnAddFriend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnFriendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(friendsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(btnChat)
                        .addGap(47, 47, 47)
                        .addComponent(btnRemove)
                        .addGap(194, 194, 194))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFriendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriendRequestActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnFriendRequestActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        // TODO add your handling code here:
        clientProcess.getExistedSingleChatRoom(clientProcess.getUser(), otherUser);
    }//GEN-LAST:event_btnChatActionPerformed

    public void receiveRoomAndGoChatInThatRoom(Room room) {
        // set room cho tien trinh clientHandler
        clientProcess.setRoom(room);
        new SingleChatFrm(clientProcess).setVisible(true);
        this.dispose();
    }

    public void createRoom() {
        Room room = new Room();
        room.setIsSingleChat(1);
        ArrayList<UserInARoom> listUserInARooms = new ArrayList<>();
        UserInARoom userInARoom1 = new UserInARoom();
        userInARoom1.setUser(clientProcess.getUser());
        listUserInARooms.add(userInARoom1);
        UserInARoom userInARoom2 = new UserInARoom();
        userInARoom2.setUser(otherUser);
        listUserInARooms.add(userInARoom2);
        room.setListUserInARoom(listUserInARooms);
        clientProcess.creatRoom(room);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnFriendRequest;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel friendsImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPhone;
    private javax.swing.JTable tblFriend;
    // End of variables declaration//GEN-END:variables
}
