/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.friend;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import model.User;
import service.ClientProcess;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Friend;

/**
 *
 * @author QUANG
 */
public class FriendRequestDialog extends javax.swing.JDialog {

    /**
     * Creates new form FriendRequestDialog
     */
    FriendFrm friendFrm;
    ArrayList<Friend> listFriend;
    ArrayList<Friend> listFriendRequest;
    User user;
    public FriendRequestDialog(java.awt.Frame parent, boolean modal, ClientProcess clientProcess, ArrayList<Friend> listFriend, User user) {
        super(parent, modal);
        initComponents();
        friendFrm = (FriendFrm) parent;
        this.listFriend = listFriend;
        this.user = user;
        clientProcess.setCurrenDialog(this);
        loadTableRequest(this.listFriend);
        
        //UI
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.getContentPane().setBackground(Color.getHSBColor(106, 52, 50));
        setTitle("Lời mời kết bạn");
        
        btnAccept.addActionListener((e)->{
            int r = tblrequest.getSelectedRow();
            Friend friendSelect = listFriendRequest.get(r);
            
            clientProcess.acceptFriend(friendSelect);    
            for(Friend i : this.listFriend){
                if( friendSelect.getId() == i.getId() ){
                    i.setFriendStatus(1);
                }
            }
            loadTableRequest(this.listFriend);
            friendFrm.setListFriend(this.listFriend);
            friendFrm.loadTableFriend(this.listFriend);
        });

        btnRemove.addActionListener((e)->{
            int r = tblrequest.getSelectedRow();
            Friend friendSelect = listFriendRequest.get(r);
            
            clientProcess.refuseFriend(friendSelect);
            for(int i = 0; i < listFriend.size();i++){
                if( this.listFriend.get(i).getId() == friendSelect.getId() ) this.listFriend.remove(i);
            }
            loadTableRequest(this.listFriend);
            friendFrm.setListFriend(this.listFriend);
        });
    }

protected void loadTableRequest(ArrayList<Friend> list ){
        ArrayList<Friend> listFR = new ArrayList<>();
        ArrayList<User> listUserDisplay = new ArrayList<>();
        for(Friend i : list){
            if(i.getFriendStatus() == 0 && i.getUser2().getId() == this.user.getId()){
                listUserDisplay.add(i.getUser1());
                listFR.add(i);
//                System.out.println(i.getId() + " " + i.getUser1().getFullName()+ " " + i.getUser2().getFullName() + "\n");
            }            
        }
        this.listFriendRequest = listFR;
        String[][] data = new String[listUserDisplay.size()][3];
        String[] columnNames = {"Full name","Email","Phone"};
        for(int i=0;i<listUserDisplay.size();i++){
            data[i][0] = listUserDisplay.get(i).getFullName()+"";
            data[i][1] = listUserDisplay.get(i).getEmail() + "";
            data[i][2] = listUserDisplay.get(i).getPhoneNo() +"" ;
        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblrequest.setModel(dtm);
    }
    private FriendRequestDialog(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblrequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblrequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblrequest);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Friend request");

        btnAccept.setText("Accept");

        btnRemove.setText("Remove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnAccept)
                        .addGap(59, 59, 59)
                        .addComponent(btnRemove)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FriendRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FriendRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FriendRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FriendRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FriendRequestDialog dialog = new FriendRequestDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblrequest;
    // End of variables declaration//GEN-END:variables
}
