/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Service.ClientProcess;
import UI.groupChat.GroupChatFrm;
import UI.groupChat.GroupChatRoomsFrm;
import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class ChatHomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form ChatFrm
     */
    private ClientProcess clientProcess;
    public ChatHomeFrm(ClientProcess clientProcess) {
        initComponents();
        this.clientProcess = clientProcess;
        
        txtUserFullName.setText("Hi, "+clientProcess.getUser().getFullName()+"!");
        
        btnSingleChat.addActionListener((e) -> {
           new SingleChatRoomsFrm(clientProcess).setVisible(true);
           this.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSingleChat = new javax.swing.JButton();
        btnGroupChat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUserFullName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSingleChat.setText("Single Chat");

        btnGroupChat.setText("Group Chat");
        btnGroupChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupChatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Chat Home");

        txtUserFullName.setText("Hi, @userFullName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGroupChat)
                            .addComponent(btnSingleChat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtUserFullName)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtUserFullName)
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnSingleChat)
                .addGap(53, 53, 53)
                .addComponent(btnGroupChat)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGroupChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupChatActionPerformed
        // TODO add your handling code here:
       new GroupChatRoomsFrm(clientProcess).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnGroupChatActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGroupChat;
    private javax.swing.JButton btnSingleChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtUserFullName;
    // End of variables declaration//GEN-END:variables
}
