/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Room;
import Model.User;
import Model.UserInARoom;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import service.ClientProcess;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class SearchUserForSingleChatFrm extends javax.swing.JFrame {

    /**
     * Creates new form SearchUserForSingleChatFrm
     */
    private ClientProcess clientProcess;
    private ArrayList<User> listUsers;
    private JFrame mainFrame = this;

    public SearchUserForSingleChatFrm(ClientProcess clientProcess) {
        initComponents();
        this.clientProcess = clientProcess;
        clientProcess.setCurrentFrame(this);
        btnBack.addActionListener((e) -> {
            new SingleChatRoomsFrm(clientProcess).setVisible(true);
            this.dispose();
        });

        clientProcess.getAllUsers();

        // tao phong moi cho user neu chua ton tai, ton tai roi thi tra ve luon
        tblUsers.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = tblUsers.getColumnModel().
                        getColumnIndexAtX(e.getX()); // 
                int row = e.getY() / tblUsers.getRowHeight();
                
                if (row < tblUsers.getRowCount() && row >= 0
                        && column < tblUsers.getColumnCount() && column >= 0) {
                    User otherUser = listUsers.get(row);
                    Room room = new Room();
                    ArrayList<UserInARoom> listUserInARooms = new ArrayList<>();
                    UserInARoom userInARoom1 = new UserInARoom();
                    userInARoom1.setUser(clientProcess.getUser());
                    listUserInARooms.add(userInARoom1);
                    UserInARoom userInARoom2 = new UserInARoom();
                    userInARoom2.setUser(otherUser);
                    listUserInARooms.add(userInARoom2);
                    room.setListUserInARoom(listUserInARooms);

                    clientProcess.creatRoom(room);
                }
            }
        });

    }

    public void receiveAllUsersAndDisplay(ArrayList<User> listUsers) {
        this.listUsers = listUsers;
        // hien thi
        String[][] data = new String[listUsers.size()][4];
        String[] columnNames = {"id", "user name", "full name", "online status"};
        for (int i = 0; i < listUsers.size(); i++) {
            User user = listUsers.get(i);
            data[i][0] = user.getId() + "";
            data[i][1] = user.getUserName();
            data[i][2] = user.getFullName();
            data[i][3] = user.getOnlineStatus() + "";
        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblUsers.setModel(dtm);
    }

    public void receiveRoomAndGoChatInThatRoom(Room room) {
        // set room cho tien trinh clientHandler
        clientProcess.setRoom(room);
        new SingleChatFrm(clientProcess).setVisible(true);
        mainFrame.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchUser = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Search User To Chat With");

        btnSearchUser.setText("Search");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnBack.setText("<--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(44, 44, 44)
                        .addComponent(btnSearchUser)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchUser))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearchUser;
    // End of variables declaration//GEN-END:variables
}
