/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Room;
import Model.User;
import Model.UserInARoom;
import Service.ClientProcess;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author LENOVO
 */
public class SingleChatFrm extends javax.swing.JFrame {

    /**
     * Creates new form SingleChatFrm
     */
    private ClientProcess clientProcess;
    public SingleChatFrm(ClientProcess clientProcess) {
        initComponents();
        this.clientProcess = clientProcess;
        
        // Lấy ra user còn lại trong phòng
        User currentUser = clientProcess.getUser();
        User theRestUserInTheRoom = new User();
        Room currentRoom = clientProcess.getRoom();
        ArrayList<UserInARoom> listUserInCurrentRoom = currentRoom.getListUserInARoom();
        for(UserInARoom u : listUserInCurrentRoom){
            if(u.getUser().getId() != currentUser.getId()){
                theRestUserInTheRoom = u.getUser();
            }
        }
        
        // In ra tên user còn lại và trạng thái đăng nhập
        labelTheRestUserName.setText(theRestUserInTheRoom.getUserName()+"("+theRestUserInTheRoom.getFullName()+")");
        if(theRestUserInTheRoom.getOnlineStatus() == 1){
             labelStatus.setText("online");
             labelStatus.setForeground(Color.GREEN);
        }else{
            labelStatus.setText("offline");
            labelStatus.setForeground(Color.red);
        }
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTheRestUserName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatScreen = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        txtMessage = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTheRestUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTheRestUserName.setText("@Name Of The Rest User");

        txtChatScreen.setEditable(false);
        txtChatScreen.setColumns(20);
        txtChatScreen.setRows(5);
        txtChatScreen.setText("user a: blabla bla\nuser b: blo blo blooo");
        jScrollPane1.setViewportView(txtChatScreen);

        btnSend.setText("Send");

        labelStatus.setText("status: online or offline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSend))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(labelTheRestUserName)
                        .addGap(44, 44, 44)
                        .addComponent(labelStatus)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTheRestUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStatus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTheRestUserName;
    private javax.swing.JTextArea txtChatScreen;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
