/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.groupChat;

import Model.Room;
import Model.User;
import Model.UserInARoom;
import Service.ClientProcess;
import UI.SingleChatFrm;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class GroupChatRoomsFrm extends javax.swing.JFrame {

    /**
     * Creates new form GroupChatRoomsFrm
     */
    private JFrame mainFrame = this;
    private ArrayList<Room> listGroupChatRooms;
    private ClientProcess clientProcess;
    public GroupChatRoomsFrm(ClientProcess clientProcess) {
        initComponents();
        this.clientProcess = clientProcess;
        int userId = clientProcess.getUser().getId();
        listGroupChatRooms = clientProcess.getGroupChatRooms(userId);
        
        
        String[][] data = new String[listGroupChatRooms.size()][2];
        String[] columnNames = {"RoomId","RoomName"};
        for(int i=0;i<listGroupChatRooms.size();i++){
            Room room = listGroupChatRooms.get(i);
            data[i][0] = room.getId()+"";
            
//            // lay ra ten cua user con lai trong phong
//            User currenUser = clientProcess.getUser();
//            User theRestUserInTheRoom = new User();
//            ArrayList<UserInARoom> listUsersInSingleChatRoom = room.getListUserInARoom();
//            for(UserInARoom u : listUsersInSingleChatRoom){
//                if(u.getUser().getId() != currenUser.getId()) theRestUserInTheRoom = u.getUser();
//            }
            data[i][1] = listGroupChatRooms.get(i).getName();
//            data[i][2] = theRestUserInTheRoom.getFullName();
//            data[i][3] = theRestUserInTheRoom.getOnlineStatus()+"";
        }
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblGroupChat.setModel(dtm);
    }

    private GroupChatRoomsFrm() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTheRestUserName = new javax.swing.JLabel();
        btnTaoPhongMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGroupChat = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTheRestUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTheRestUserName.setText("Group chat gan day:");

        btnTaoPhongMoi.setText("Tao phong moi");
        btnTaoPhongMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhongMoiActionPerformed(evt);
            }
        });

        tblGroupChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Lap Trinh Mang nhom 11"},
                {"2", "Lap Trinh Web"},
                {"3", "Phan tich thiet ke"}
            },
            new String [] {
                "id", "name"
            }
        ));
        tblGroupChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupChatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGroupChat);

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(labelTheRestUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTaoPhongMoi)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaoPhongMoi)
                    .addComponent(labelTheRestUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblGroupChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupChatMouseClicked
        // TODO add your handling code here:
         int column = tblGroupChat.getColumnModel().
                        getColumnIndexAtX(evt.getX()); // 
                int row = evt.getY()/tblGroupChat.getRowHeight(); 
 
                if (row < tblGroupChat.getRowCount() && row >= 0 && 
                            column < tblGroupChat.getColumnCount() && column >= 0) {
                   Room room = listGroupChatRooms.get(row);
                   System.out.println("room" + room.getListUserInARoom().get(0).getUser().getFullName());
                   clientProcess.setRoom(room);
                   new GroupChatFrm(clientProcess).setVisible(true);
                   mainFrame.dispose();
                }
    }//GEN-LAST:event_tblGroupChatMouseClicked

    private void btnTaoPhongMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhongMoiActionPerformed
        // TODO add your handling code here:
        new CreateNewGroupFrm(clientProcess).setVisible(true);
    }//GEN-LAST:event_btnTaoPhongMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupChatRoomsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupChatRoomsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupChatRoomsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupChatRoomsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupChatRoomsFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTaoPhongMoi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTheRestUserName;
    private javax.swing.JTable tblGroupChat;
    // End of variables declaration//GEN-END:variables
}
